Repository thoth-station/ray-ml-worker, pull requests merged in 2022-06, with the labels that each got.

#21 add tensorflow deps to pipfiles
  Pipfile
  Pipfile.lock
Labels: lgtm

#23 add reqs for ray data
  Pipfile
  Pipfile.lock
Labels: lgtm, approved, needs-ok-to-test, size/L

#25 Release of version 0.2.0
  CHANGELOG.md
  thoth/ray-ml-worker/__init__.py
Labels: approved, ok-to-test
